spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev
  application:
    name: microcloud-config-client-8201
---
spring:
  profiles: beta
  application:
    name: microcloud-config-client-8201