spring:
  profiles:
   active:
   - dev
---
spring:
  profiles: dev
  application:
    name: microcloud-config-eureka-client-7001
---
spring:
  profiles: beta
  application:
    name: microcloud-config-eureka-client-7001